version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "payload-topic:3:1"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEPEPER_CONNECT: zookeeper:2181