kafka:
  broker: 192.168.99.101

spring:
  kafka:
    producer:
      bootstrap-servers: ${kafka.broker}:9092
      client-id: kafka-payload-producer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
